name: Cypress Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress - Cadastro
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: cypress/e2e/cadastro/cadastro.feature

      - name: Run Cypress - Busca profissional
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: cypress/e2e/busca-profissional/busca-profissional.feature

      - name: Run Cypress - Recuperação de senha
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: cypress/e2e/recuperacao-senha/recuperacao-senha.feature

      - name: Upload Cypress screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots